version: "3"

services:
  app:
    container_name: linkstorage_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    restart: always
    command: sh -c "python3 manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 config.wsgi"
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - staticfiles:/usr/src/app/static
    depends_on:
      - db

  db:
    container_name: linkstorage_db
    image: postgres:latest
    restart: always
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  celery:
    container_name: linkstorage_celery
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    restart: always
    command: celery -A config worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - app
      - rabbitmq

  rabbitmq:
    container_name: linkstorage_rabbitmq
    image: rabbitmq:latest
    restart: always
    expose:
      - ${RABBITMQ_PORT}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    container_name: linkstorage_nginx
    image: nginx:latest
    restart: always
    expose:
      - ${NGINX_PORT}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - staticfiles:/static/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app


volumes:
  db_data:
  rabbitmq_data:
  staticfiles: