# Generated by Django 4.1.7 on 2023-03-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='link_url',
        ),
    ]
